# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_lunch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreapplication',
            options={'ordering': ('created_date',)},
        ),
        migrations.RemoveField(
            model_name='coreapplication',
            name='ssn_primary_earner',
        ),
        migrations.RemoveField(
            model_name='coreapplication',
            name='total_household_members',
        ),
        migrations.AddField(
            model_name='adult',
            name='is_signer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreapplication',
            name='assistance_type',
            field=models.CharField(choices=[('SNAP', 'SNAP'), ('FDPIR', 'FDPIR'), ('TANF', 'TANF')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coreapplication',
            name='children_are_american_indian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreapplication',
            name='children_are_asian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreapplication',
            name='children_are_black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreapplication',
            name='children_are_hispanic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreapplication',
            name='children_are_pacific_islander',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreapplication',
            name='children_are_white',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreapplication',
            name='children_not_hispanic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreapplication',
            name='ssn_signer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adult', to='school_lunch.CoreApplication'),
        ),
        migrations.AlterField(
            model_name='adult',
            name='other_income_frequency',
            field=models.CharField(choices=[('weekly', 'weekly'), ('biweekly', 'biweekly'), ('twice-monthly', 'twice-monthly'), ('monthly', 'monthly')], max_length=15),
        ),
        migrations.AlterField(
            model_name='adult',
            name='public_income_frequency',
            field=models.CharField(choices=[('weekly', 'weekly'), ('biweekly', 'biweekly'), ('twice-monthly', 'twice-monthly'), ('monthly', 'monthly')], max_length=15),
        ),
        migrations.AlterField(
            model_name='adult',
            name='work_income_frequency',
            field=models.CharField(choices=[('weekly', 'weekly'), ('biweekly', 'biweekly'), ('twice-monthly', 'twice-monthly'), ('monthly', 'monthly')], max_length=15),
        ),
        migrations.AlterField(
            model_name='child',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='school_lunch.CoreApplication'),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='assistance_case_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='child_income_frequency',
            field=models.CharField(choices=[('weekly', 'weekly'), ('biweekly', 'biweekly'), ('twice-monthly', 'twice-monthly'), ('monthly', 'monthly')], max_length=15),
        ),
    ]
