# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_lunch', '0003_auto_20160207_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adults', to='school_lunch.CoreApplication'),
        ),
        migrations.AlterField(
            model_name='child',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='school_lunch.CoreApplication'),
        ),
    ]
