# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_lunch', '0004_auto_20160207_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_head_start',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
