# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_lunch', '0005_child_is_head_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'children'},
        ),
        migrations.AlterModelOptions(
            name='coreapplication',
            options={'ordering': ('created_date',), 'verbose_name': 'Application'},
        ),
        migrations.AlterField(
            model_name='adult',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='other_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='other_income_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'weekly'), ('biweekly', 'biweekly'), ('twice-monthly', 'twice-monthly'), ('monthly', 'monthly')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='public_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='public_income_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'weekly'), ('biweekly', 'biweekly'), ('twice-monthly', 'twice-monthly'), ('monthly', 'monthly')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='work_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adult',
            name='work_income_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'weekly'), ('biweekly', 'biweekly'), ('twice-monthly', 'twice-monthly'), ('monthly', 'monthly')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='is_foster',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='is_head_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='is_homeless_migrant_runaway',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='child',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='child_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='child_income_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'weekly'), ('biweekly', 'biweekly'), ('twice-monthly', 'twice-monthly'), ('monthly', 'monthly')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coreapplication',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
