# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_lunch', '0006_auto_20160222_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreapplication',
            name='assistance_type',
            field=models.CharField(blank=True, choices=[('SNAP', 'SNAP'), ('FDPIR', 'FDPIR'), ('TANF', 'TANF')], max_length=10, null=True),
        ),
    ]
